name: Pipeline with Docker Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t my-image-name:latest .

    - name: Push Docker image
      run: |
        docker tag my-image-name:latest lesliearjona/my-image-name:latest
        docker push lesliearjona/my-image-name:latest

    - name: Run tests
      run: |
          pytest tests/

    - name: Deploy to remote server
      run: |
        ssh user@your-server-ip "docker pull lesliearjona/my-image-name:latest && docker stop my-app || true && docker run -d --name my-app -p 80:80 lesliearjona/my-image-name:latest"
        
        
      
