name: Pipeline with Docker Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Load .env file
      run: |
        export $(cat .env | xargs)
    
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      
    - name: Build Docker image
      run: |
        docker build -t my-image-name:latest .

    - name: Push Docker image
      run: |
        docker tag my-image-name:latest username/my-image-name:latest
        docker push username/my-image-name:latest
